# Generated by Django 4.1.1 on 2022-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.PositiveIntegerField(verbose_name="ID пользователя"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя пользователя"),
                ),
            ],
            options={
                "verbose_name_plural": "Телеграмм пользователи",
            },
        ),
    ]
