# Generated by Django 4.1.1 on 2022-10-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramusers",
            options={
                "verbose_name": "Телеграмм пользователь",
                "verbose_name_plural": "Телеграмм пользователи",
            },
        ),
    ]
