# Generated by Django 4.1.1 on 2022-10-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_alter_telegramusers_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramusers",
            options={
                "verbose_name": "Телеграм пользователь",
                "verbose_name_plural": "Телеграм пользователи",
            },
        ),
    ]
