# Generated by Django 4.1.1 on 2022-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_alter_telegramusers_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramusers",
            name="external_id",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="ID пользователя"
            ),
        ),
    ]
