# Generated by Django 4.1.1 on 2022-09-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="second_name",
        ),
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(
                default=1, help_text="Введите фамилию автора", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(help_text="Введите имя автора", max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="descript",
            field=models.TextField(help_text="Введите описаниние книги"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(help_text="Введите название книги", max_length=200),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Введите наименование жанра", max_length=200
            ),
        ),
    ]
