# Generated by Django 4.1.1 on 2022-09-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_author_second_name_author_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="file",
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя автора", max_length=200, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(
                help_text="Введите фамилию автора",
                max_length=200,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="descript",
            field=models.TextField(
                help_text="Введите описаниние книги", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="catalog.genre", verbose_name="Жанр"),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(
                help_text="Введите название книги",
                max_length=200,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Введите наименование жанра",
                max_length=200,
                verbose_name="Жанр",
            ),
        ),
    ]
