# Generated by Django 4.1.1 on 2022-09-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_book_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="genres",
        ),
    ]
