# Generated by Django 4.1.1 on 2022-10-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_book_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Авторы"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name_plural": "Книги"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name_plural": "Жанры"},
        ),
    ]
